/*
 * weapons27.h
 *
 * ShowEQ Distributed under GPL
 * http://seq.sourceforge.net/
 */
    NULL,                 // 0x00
    NULL,                 // 0x01
    NULL,                 // 0x02
    NULL,                 // 0x03
    NULL,                 // 0x04
    NULL,                 // 0x05
    NULL,                 // 0x06
    NULL,                 // 0x07
    NULL,                 // 0x08
    NULL,                 // 0x09
    NULL,                 // 0x0a
    NULL,                 // 0x0b
    NULL,                 // 0x0c
    NULL,                 // 0x0d
    NULL,                 // 0x0e
    NULL,                 // 0x0f
    NULL,                 // 0x10
    NULL,                 // 0x11
    NULL,                 // 0x12
    NULL,                 // 0x13
    NULL,                 // 0x14
    NULL,                 // 0x15
    NULL,                 // 0x16
    NULL,                 // 0x17
    NULL,                 // 0x18
    NULL,                 // 0x19
    NULL,                 // 0x1a
    "Stone Axe",          // 0x1b
    "Stone Hammer",       // 0x1c
    NULL,                 // 0x1d
    NULL,                 // 0x1e
    NULL,                 // 0x1f
    NULL,                 // 0x20
    NULL,                 // 0x21
    NULL,                 // 0x22
    NULL,                 // 0x23
    NULL,                 // 0x24
    NULL,                 // 0x25
    NULL,                 // 0x26
    NULL,                 // 0x27
    NULL,                 // 0x28
    NULL,                 // 0x29
    NULL,                 // 0x2a
    NULL,                 // 0x2b
    NULL,                 // 0x2c
    NULL,                 // 0x2d
    NULL,                 // 0x2e
    NULL,                 // 0x2f
    NULL,                 // 0x30
    NULL,                 // 0x31
    NULL,                 // 0x32
    NULL,                 // 0x33
    NULL,                 // 0x34
    NULL,                 // 0x35
    NULL,                 // 0x36
    NULL,                 // 0x37
    NULL,                 // 0x38
    NULL,                 // 0x39
    NULL,                 // 0x3a
    NULL,                 // 0x3b
    NULL,                 // 0x3c
    NULL,                 // 0x3d
    NULL,                 // 0x3e
    NULL,                 // 0x3f
    NULL,                 // 0x40
    NULL,                 // 0x41
    NULL,                 // 0x42
    NULL,                 // 0x43
    NULL,                 // 0x44
    NULL,                 // 0x45
    NULL,                 // 0x46
    NULL,                 // 0x47
    NULL,                 // 0x48
    NULL,                 // 0x49
    NULL,                 // 0x4a
    NULL,                 // 0x4b
    NULL,                 // 0x4c
    NULL,                 // 0x4d
    NULL,                 // 0x4e
    NULL,                 // 0x4f
    NULL,                 // 0x50
    NULL,                 // 0x51
    NULL,                 // 0x52
    NULL,                 // 0x53
    NULL,                 // 0x54
    NULL,                 // 0x55
    NULL,                 // 0x56
    NULL,                 // 0x57
    NULL,                 // 0x58
    NULL,                 // 0x59
    NULL,                 // 0x5a
    NULL,                 // 0x5b
    NULL,                 // 0x5c
    NULL,                 // 0x5d
    NULL,                 // 0x5e
    NULL,                 // 0x5f
    NULL,                 // 0x60
    NULL,                 // 0x61
    NULL,                 // 0x62
    NULL,                 // 0x63
    NULL,                 // 0x64
    NULL,                 // 0x65
    NULL,                 // 0x66
    NULL,                 // 0x67
    NULL,                 // 0x68
    NULL,                 // 0x69
    NULL,                 // 0x6a
    NULL,                 // 0x6b
    NULL,                 // 0x6c
    NULL,                 // 0x6d
    NULL,                 // 0x6e
    NULL,                 // 0x6f
    NULL,                 // 0x70
    NULL,                 // 0x71
    NULL,                 // 0x72
    NULL,                 // 0x73
    NULL,                 // 0x74
    "Wood Spear",         // 0x75
    NULL,                 // 0x76
    NULL,                 // 0x77
    NULL,                 // 0x78
    NULL,                 // 0x79
    "Stone Spear",        // 0x7a
    NULL,                 // 0x7b
    NULL,                 // 0x7c
    "Bone Spear",         // 0x7d
    NULL,                 // 0x7e
    NULL,                 // 0x7f
